apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cluster-register
spec:
  components:
    - name: register
      type: cluster-register
      properties:
        name: spoke-kubeconfig
        ns: default